# Generated by Django 3.0.2 on 2020-05-09 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predictor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='road',
            name='location',
            field=models.TextField(default=None),
        ),
        migrations.AddField(
            model_name='road',
            name='road_image_predicted',
            field=models.ImageField(default=None, upload_to='images/'),
        ),
    ]
