# Generated by Django 3.0.2 on 2020-06-04 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predictor', '0002_auto_20200509_0426'),
    ]

    operations = [
        migrations.AddField(
            model_name='road',
            name='priority',
            field=models.TextField(choices=[('L', 'low'), ('H', 'high')], default='low'),
        ),
        migrations.AddField(
            model_name='road',
            name='work_status',
            field=models.TextField(choices=[(1, 'Yet to begin'), (2, 'On Progress'), (3, 'Completed')], default='Yet to begin'),
        ),
    ]
